-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgRSTUjgESQRDDTYpt
tsODKPb9LqXqt6A0L28CBnJxDJmgCgYIKoZIzj0DAQehRANCAAQkKPvINdzBxLll
upn7WJ1Cu6wo97Pk3joIUAqkE0w5ReYQVVUuaIkuRs8tB2fMOV+J36V9SI/DitWc
VNNIzopK
-----END PRIVATE KEY-----